//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer CBuffer_Pixel_Gradient
// {
//
//   float2 m_p;                        // Offset:    0 Size:     8
//   float2 m_v;                        // Offset:    8 Size:     8
//   int m_func;                        // Offset:   16 Size:     4
//   int m_num_stops;                   // Offset:   20 Size:     4
//   float4 m_stop_colors[16];          // Offset:   32 Size:   256
//   float m_stop_positions[16];        // Offset:  288 Size:   244
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// CBuffer_Pixel_Gradient            cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// COLOR                    0   xyzw        1     NONE   float   xyzw
// TEXCOORD                 0   xy          2     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed | skipOptimization
dcl_constantbuffer CB0[34], dynamicIndexed
dcl_input_ps linear v1.xyzw
dcl_input_ps linear v2.xy
dcl_output o0.xyzw
dcl_temps 5
//
// Initial variable locations:
//   v0.x <- input.position.x; v0.y <- input.position.y; v0.z <- input.position.z; v0.w <- input.position.w; 
//   v1.x <- input.color.x; v1.y <- input.color.y; v1.z <- input.color.z; v1.w <- input.color.w; 
//   v2.x <- input.tex_coord.x; v2.y <- input.tex_coord.y; 
//   o0.x <- <main return value>.x; o0.y <- <main return value>.y; o0.z <- <main return value>.z; o0.w <- <main return value>.w
//
#line 34 "C:\Users\cafeed28\Development\RmlUi\Backends\RmlUi_D3D11\shader_pixel_gradient.hlsl"
mov r0.x, l(0)  // r0.x <- t

#line 36
ieq r0.y, cb0[1].x, l(0)
ieq r0.z, cb0[1].x, l(3)
or r0.y, r0.z, r0.y
if_nz r0.y

#line 37
  dp2 r0.y, cb0[0].zwzz, cb0[0].zwzz  // r0.y <- dist_square

#line 38
  mov r0.zw, -cb0[0].xxxy
  add r0.zw, r0.zzzw, v2.xxxy  // r0.z <- V.x; r0.w <- V.y

#line 39
  dp2 r0.z, cb0[0].zwzz, r0.zwzz
  div r0.x, r0.z, r0.y

#line 40
else 

#line 36
  mov r0.y, cb0[1].x  // r0.y <- m_func

#line 40
  ieq r0.z, r0.y, l(1)
  ieq r0.w, r0.y, l(4)
  or r0.z, r0.w, r0.z
  if_nz r0.z

#line 41
    mov r0.zw, -cb0[0].xxxy
    add r0.zw, r0.zzzw, v2.xxxy  // r0.z <- V.x; r0.w <- V.y

#line 42
    mul r0.zw, r0.zzzw, cb0[0].zzzw
    dp2 r0.z, r0.zwzz, r0.zwzz
    sqrt r0.x, r0.z

#line 43
  else 
    ieq r0.z, r0.y, l(2)
    ieq r0.y, r0.y, l(5)
    or r0.y, r0.y, r0.z
    if_nz r0.y

#line 44
      mov r1.z, -cb0[0].w  // r1.z <- R._m10
      mov r1.xyw, cb0[0].zwzz  // r1.x <- R._m00; r1.y <- R._m01; r1.w <- R._m11

#line 45
      mov r0.yz, -cb0[0].xxyx
      add r0.yz, r0.yyzy, v2.xxyx
      dp2 r0.w, r1.xyxx, r0.yzyy  // r0.w <- V.x
      dp2 r0.y, r1.zwzz, r0.yzyy  // r0.y <- V.y

#line 46
      mov r0.z, -r0.w
      mov r0.w, -r0.z
      max r0.w, r0.w, r0.z
      mov r1.x, -r0.y
      max r1.y, r0.y, r1.x
      min r1.z, r0.w, r1.y
      max r1.w, r0.w, r1.y
      div r1.w, l(1.000000, 1.000000, 1.000000, 1.000000), r1.w
      mul r1.z, r1.w, r1.z
      mul r1.w, r1.z, r1.z
      mul r2.x, r1.w, l(0.020835)
      add r2.x, r2.x, l(-0.085133)
      mul r2.x, r1.w, r2.x
      add r2.x, r2.x, l(0.180141)
      mul r2.x, r1.w, r2.x
      add r2.x, r2.x, l(-0.330299)
      mul r1.w, r1.w, r2.x
      add r1.w, r1.w, l(0.999866)
      mul r1.z, r1.w, r1.z
      lt r0.w, r1.y, r0.w
      mul r1.y, r1.z, l(-2.000000)
      add r1.y, r1.y, l(1.570796)
      and r0.w, r0.w, r1.y
      add r0.w, r1.z, r0.w
      lt r1.x, r0.y, r1.x
      and r1.x, r1.x, l(0xc0490fdb)
      add r0.w, r0.w, r1.x
      min r1.x, r0.y, r0.z
      max r0.y, r0.y, r0.z
      mov r0.z, -r1.x
      lt r0.z, r1.x, r0.z
      mov r1.x, -r0.y
      ge r0.y, r0.y, r1.x
      and r0.y, r0.y, r0.z
      mov r0.z, -r0.w
      movc r0.y, r0.y, r0.z, r0.w
      div r0.y, r0.y, l(6.283185)
      add r0.x, r0.y, l(0.500000)

#line 47
    endif 
  endif 
endif 

#line 49
ieq r0.y, cb0[1].x, l(3)
ieq r0.z, cb0[1].x, l(4)
or r0.y, r0.z, r0.y
ieq r0.z, cb0[1].x, l(5)
or r0.y, r0.z, r0.y
if_nz r0.y

#line 52
  mov r0.y, cb0[18].x  // r0.y <- t0

#line 53
  ineg r0.z, l(1)
  iadd r0.z, r0.z, cb0[1].y
  mov r0.z, cb0[r0.z + 18].x  // r0.z <- t1

#line 54
  mov r0.w, -r0.y
  add r0.w, r0.w, r0.x
  mov r1.x, -r0.y
  add r0.z, r0.z, r1.x
  div r0.w, r0.w, r0.z
  mov r1.x, -r0.w
  max r1.y, r0.w, r1.x
  ge r0.w, r0.w, r1.x
  frc r1.x, r1.y
  mov r1.y, -r1.x
  movc r0.w, r0.w, r1.x, r1.y
  mul r0.z, r0.z, r0.w
  add r0.x, r0.z, r0.y

#line 55
endif 

#line 57
nop 
mov r0.x, r0.x

#line 24
mov r1.xyzw, cb0[2].xyzw  // r1.x <- color.x; r1.y <- color.y; r1.z <- color.z; r1.w <- color.w

#line 26
mov r0.y, l(1)  // r0.y <- i
mov r2.xyzw, r1.xyzw  // r2.x <- color.x; r2.y <- color.y; r2.z <- color.z; r2.w <- color.w
mov r0.z, r0.y  // r0.z <- i
loop 
  ilt r0.w, r0.z, cb0[1].y
  breakc_z r0.w

#line 27
  mov r0.w, r0.z
  ineg r3.x, l(1)
  iadd r3.x, r0.z, r3.x
  mov r3.x, -cb0[r3.x + 18].x
  add r3.y, r3.x, cb0[r0.z + 18].x
  add r3.x, r0.x, r3.x
  div r3.y, l(1.000000, 1.000000, 1.000000, 1.000000), r3.y
  mul r3.x, r3.y, r3.x
  max r3.x, r3.x, l(0.000000)
  min r3.x, r3.x, l(1.000000)
  mul r3.y, r3.x, l(-2.000000)
  add r3.y, r3.y, l(3.000000)
  mul r3.x, r3.x, r3.x
  mul r3.x, r3.x, r3.y
  mov r4.xyzw, -r2.xyzw
  add r4.xyzw, r4.xyzw, cb0[r0.w + 2].xyzw
  mul r3.xyzw, r3.xxxx, r4.xyzw
  add r2.xyzw, r2.xyzw, r3.xyzw

#line 28
  iadd r0.z, r0.z, l(1)
endloop 

#line 30
mov r2.xyzw, r2.xyzw  // r2.x <- <mix_stop_colors return value>.x; r2.y <- <mix_stop_colors return value>.y; r2.z <- <mix_stop_colors return value>.z; r2.w <- <mix_stop_colors return value>.w

#line 57
mul o0.xyzw, r2.xyzw, v1.xyzw
ret 
// Approximately 129 instruction slots used
