//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer CBuffer_Pixel_Creation
// {
//
//   float m_value;                     // Offset:    0 Size:     4
//   float2 m_dimensions;               // Offset:    4 Size:     8
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// CBuffer_Pixel_Creation            cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// COLOR                    0   xyzw        1     NONE   float      w
// TEXCOORD                 0   xy          2     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed | skipOptimization
dcl_constantbuffer CB0[1], immediateIndexed
dcl_input_ps linear v1.w
dcl_input_ps linear v2.xy
dcl_output o0.xyzw
dcl_temps 4
//
// Initial variable locations:
//   v0.x <- input.position.x; v0.y <- input.position.y; v0.z <- input.position.z; v0.w <- input.position.w; 
//   v1.x <- input.color.x; v1.y <- input.color.y; v1.z <- input.color.z; v1.w <- input.color.w; 
//   v2.x <- input.tex_coord.x; v2.y <- input.tex_coord.y; 
//   o0.x <- <main return value>.x; o0.y <- <main return value>.y; o0.z <- <main return value>.z; o0.w <- <main return value>.w
//
#line 12 "C:\Users\cafeed28\Development\RmlUi\Backends\RmlUi_D3D11\shader_pixel_creation.hlsl"
mov r0.x, cb0[0].x  // r0.x <- t

#line 16
mov r0.y, l(0)  // r0.y <- i

#line 17
mov r1.xy, v2.xyxx  // r1.x <- p.x; r1.y <- p.y

#line 18
mov r1.xy, r1.xyxx  // r1.x <- uv.x; r1.y <- uv.y

#line 19
mov r0.zw, l(-0.000000,-0.000000,-0.500000,-0.500000)
add r2.yz, r0.zzwz, r1.xxyx  // r2.y <- p.x; r2.z <- p.y

#line 20
div r0.z, cb0[0].y, cb0[0].z
mul r2.x, r0.z, r2.y  // r2.x <- p.x

#line 21
itof r0.z, r0.y
mul r0.z, r0.z, l(0.070000)
add r0.z, r0.z, r0.x  // r0.z <- z

#line 22
dp2 r0.w, r2.xzxx, r2.xzxx
sqrt r0.w, r0.w  // r0.w <- l

#line 23
div r1.zw, r2.xxxz, r0.wwww
sincos r2.x, null, r0.z
add r2.x, r2.x, l(1.000000)
mul r1.zw, r1.zzzw, r2.xxxx
mul r0.w, r0.w, l(9.000000)
mov r2.x, -r0.z
add r0.w, r0.w, r2.x
mov r0.z, -r0.z
add r0.z, r0.z, r0.w
sincos r0.z, null, r0.z
mov r0.w, -r0.z
max r0.z, r0.w, r0.z
mul r0.zw, r0.zzzz, r1.zzzw
add r0.zw, r0.zzzw, r1.xxxy  // r0.z <- uv.x; r0.w <- uv.y

#line 25
div r1.xy, r0.zwzz, l(1.000000, 1.000000, 0.000000, 0.000000)
round_ni r1.xy, r1.xyxx
mul r1.xy, r1.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
mov r1.xy, -r1.xyxx
add r0.zw, r0.zzzw, r1.xxxy  // r0.z <- wrappedUV.x; r0.w <- wrappedUV.y

#line 26
mov r1.xy, l(-0.500000,-0.500000,-0.000000,-0.000000)
add r0.zw, r0.zzzw, r1.xxxy
dp2 r0.z, r0.zwzz, r0.zwzz
sqrt r0.z, r0.z
div r1.x, l(0.010000), r0.z  // r1.x <- c.x

#line 27
iadd r0.y, r0.y, l(1)

#line 17
mov r2.xy, v2.xyxx  // r2.x <- p.x; r2.y <- p.y

#line 18
mov r2.xy, r2.xyxx  // r2.x <- uv.x; r2.y <- uv.y

#line 19
mov r0.zw, l(-0.000000,-0.000000,-0.500000,-0.500000)
add r3.yz, r0.zzwz, r2.xxyx  // r3.y <- p.x; r3.z <- p.y

#line 20
div r0.z, cb0[0].y, cb0[0].z
mul r3.x, r0.z, r3.y  // r3.x <- p.x

#line 21
itof r0.z, r0.y
mul r0.z, r0.z, l(0.070000)
add r0.z, r0.z, r0.x  // r0.z <- z

#line 22
dp2 r0.w, r3.xzxx, r3.xzxx
sqrt r0.w, r0.w  // r0.w <- l

#line 23
div r2.zw, r3.xxxz, r0.wwww
sincos r1.w, null, r0.z
add r1.w, r1.w, l(1.000000)
mul r2.zw, r1.wwww, r2.zzzw
mul r0.w, r0.w, l(9.000000)
mov r1.w, -r0.z
add r0.w, r0.w, r1.w
mov r0.z, -r0.z
add r0.z, r0.z, r0.w
sincos r0.z, null, r0.z
mov r0.w, -r0.z
max r0.z, r0.w, r0.z
mul r0.zw, r0.zzzz, r2.zzzw
add r0.zw, r0.zzzw, r2.xxxy  // r0.z <- uv.x; r0.w <- uv.y

#line 25
div r2.xy, r0.zwzz, l(1.000000, 1.000000, 0.000000, 0.000000)
round_ni r2.xy, r2.xyxx
mul r2.xy, r2.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
mov r2.xy, -r2.xyxx
add r0.zw, r0.zzzw, r2.xxxy  // r0.z <- wrappedUV.x; r0.w <- wrappedUV.y

#line 26
mov r2.xy, l(-0.500000,-0.500000,-0.000000,-0.000000)
add r0.zw, r0.zzzw, r2.xxxy
dp2 r0.z, r0.zwzz, r0.zwzz
sqrt r0.z, r0.z
div r1.y, l(0.010000), r0.z  // r1.y <- c.y

#line 27
iadd r0.y, r0.y, l(1)

#line 17
mov r2.xy, v2.xyxx  // r2.x <- p.x; r2.y <- p.y

#line 18
mov r2.xy, r2.xyxx  // r2.x <- uv.x; r2.y <- uv.y

#line 19
mov r0.zw, l(-0.000000,-0.000000,-0.500000,-0.500000)
add r3.yz, r0.zzwz, r2.xxyx  // r3.y <- p.x; r3.z <- p.y

#line 20
div r0.z, cb0[0].y, cb0[0].z
mul r3.x, r0.z, r3.y  // r3.x <- p.x

#line 21
itof r0.y, r0.y
mul r0.y, r0.y, l(0.070000)
add r0.x, r0.y, r0.x  // r0.x <- z

#line 22
dp2 r0.y, r3.xzxx, r3.xzxx
sqrt r0.y, r0.y  // r0.y <- l

#line 23
div r0.zw, r3.xxxz, r0.yyyy
sincos r1.w, null, r0.x
add r1.w, r1.w, l(1.000000)
mul r0.zw, r0.zzzw, r1.wwww
mul r1.w, r0.y, l(9.000000)
mov r2.z, -r0.x
add r1.w, r1.w, r2.z
mov r0.x, -r0.x
add r0.x, r0.x, r1.w
sincos r0.x, null, r0.x
mov r1.w, -r0.x
max r0.x, r0.x, r1.w
mul r0.xz, r0.xxxx, r0.zzwz
add r0.xz, r0.xxzx, r2.xxyx  // r0.x <- uv.x; r0.z <- uv.y

#line 25
div r2.xy, r0.xzxx, l(1.000000, 1.000000, 0.000000, 0.000000)
round_ni r2.xy, r2.xyxx
mul r2.xy, r2.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
mov r2.xy, -r2.xyxx
add r0.xz, r0.xxzx, r2.xxyx  // r0.x <- wrappedUV.x; r0.z <- wrappedUV.y

#line 26
mov r2.xy, l(-0.500000,-0.500000,-0.000000,-0.000000)
add r0.xz, r0.xxzx, r2.xxyx
dp2 r0.x, r0.xzxx, r0.xzxx
sqrt r0.x, r0.x
div r1.z, l(0.010000), r0.x  // r1.z <- c.z

#line 29
div o0.xyz, r1.xyzx, r0.yyyy
mov o0.w, v1.w
ret 
// Approximately 112 instruction slots used
