//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer CBuffer_Vertex_Blur
// {
//
//   float2 m_texel_offset;             // Offset:    0 Size:     8
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// CBuffer_Vertex_Blur               cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xy  
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
// TEXCOORD                 0   xy          1     NONE   float   xy  
// TEXCOORD                 1   xy          2     NONE   float   xy  
// TEXCOORD                 2   xy          3     NONE   float   xy  
// TEXCOORD                 3   xy          4     NONE   float   xy  
// TEXCOORD                 4   xy          5     NONE   float   xy  
// TEXCOORD                 5   xy          6     NONE   float   xy  
// TEXCOORD                 6   xy          7     NONE   float   xy  
//
vs_5_0
dcl_globalFlags refactoringAllowed | skipOptimization
dcl_constantbuffer CB0[1], immediateIndexed
dcl_input v0.xy
dcl_input v1.xy
dcl_output_siv o0.xyzw, position
dcl_output o1.xy
dcl_output o2.xy
dcl_output o3.xy
dcl_output o4.xy
dcl_output o5.xy
dcl_output o6.xy
dcl_output o7.xy
dcl_temps 5
//
// Initial variable locations:
//   v0.x <- input.position.x; v0.y <- input.position.y; v0.z <- input.position.z; v0.w <- input.position.w; 
//   v1.x <- input.tex_coord.x; v1.y <- input.tex_coord.y; 
//   o7.x <- <main return value>.tex_coord[6].x; o7.y <- <main return value>.tex_coord[6].y; 
//   o6.x <- <main return value>.tex_coord[5].x; o6.y <- <main return value>.tex_coord[5].y; 
//   o5.x <- <main return value>.tex_coord[4].x; o5.y <- <main return value>.tex_coord[4].y; 
//   o4.x <- <main return value>.tex_coord[3].x; o4.y <- <main return value>.tex_coord[3].y; 
//   o3.x <- <main return value>.tex_coord[2].x; o3.y <- <main return value>.tex_coord[2].y; 
//   o2.x <- <main return value>.tex_coord[1].x; o2.y <- <main return value>.tex_coord[1].y; 
//   o1.x <- <main return value>.tex_coord[0].x; o1.y <- <main return value>.tex_coord[0].y; 
//   o0.x <- <main return value>.position.x; o0.y <- <main return value>.position.y; o0.z <- <main return value>.position.z; o0.w <- <main return value>.position.w
//
#line 10 "C:\Users\cafeed28\Development\RmlUi\Backends\RmlUi_D3D11\shader_vertex_blur.hlsl"
mov r0.x, l(0)  // r0.x <- i

#line 11
ineg r0.y, l(4)
iadd r0.y, r0.y, r0.x
iadd r0.y, r0.y, l(1)
itof r0.y, r0.y
mul r0.yz, r0.yyyy, cb0[0].xxyx
mov r0.yz, -r0.yyzy
add r0.yz, r0.yyzy, v1.xxyx  // r0.y <- output.tex_coord[0].x; r0.z <- output.tex_coord[0].y
iadd r0.x, r0.x, l(1)
ineg r0.w, l(4)
iadd r0.w, r0.w, r0.x
iadd r0.w, r0.w, l(1)
itof r0.w, r0.w
mul r1.xy, r0.wwww, cb0[0].xyxx
mov r1.xy, -r1.xyxx
add r1.xy, r1.xyxx, v1.xyxx  // r1.x <- output.tex_coord[1].x; r1.y <- output.tex_coord[1].y
iadd r0.x, r0.x, l(1)
ineg r0.w, l(4)
iadd r0.w, r0.w, r0.x
iadd r0.w, r0.w, l(1)
itof r0.w, r0.w
mul r1.zw, r0.wwww, cb0[0].xxxy
mov r1.zw, -r1.zzzw
add r1.zw, r1.zzzw, v1.xxxy  // r1.z <- output.tex_coord[2].x; r1.w <- output.tex_coord[2].y
iadd r0.x, r0.x, l(1)
ineg r0.w, l(4)
iadd r0.w, r0.w, r0.x
iadd r0.w, r0.w, l(1)
itof r0.w, r0.w
mul r2.xy, r0.wwww, cb0[0].xyxx
mov r2.xy, -r2.xyxx
add r2.xy, r2.xyxx, v1.xyxx  // r2.x <- output.tex_coord[3].x; r2.y <- output.tex_coord[3].y
iadd r0.x, r0.x, l(1)
ineg r0.w, l(4)
iadd r0.w, r0.w, r0.x
iadd r0.w, r0.w, l(1)
itof r0.w, r0.w
mul r2.zw, r0.wwww, cb0[0].xxxy
mov r2.zw, -r2.zzzw
add r2.zw, r2.zzzw, v1.xxxy  // r2.z <- output.tex_coord[4].x; r2.w <- output.tex_coord[4].y
iadd r0.x, r0.x, l(1)
ineg r0.w, l(4)
iadd r0.w, r0.w, r0.x
iadd r0.w, r0.w, l(1)
itof r0.w, r0.w
mul r3.xy, r0.wwww, cb0[0].xyxx
mov r3.xy, -r3.xyxx
add r3.xy, r3.xyxx, v1.xyxx  // r3.x <- output.tex_coord[5].x; r3.y <- output.tex_coord[5].y
iadd r0.x, r0.x, l(1)
ineg r0.w, l(4)
iadd r0.x, r0.w, r0.x
iadd r0.x, r0.x, l(1)
itof r0.x, r0.x
mul r0.xw, r0.xxxx, cb0[0].xxxy
mov r0.xw, -r0.xxxw
add r0.xw, r0.xxxw, v1.xxxy  // r0.x <- output.tex_coord[6].x; r0.w <- output.tex_coord[6].y

#line 13
mov r4.xy, v0.xyxx  // r4.x <- output.position.x; r4.y <- output.position.y
mov r4.zw, l(0,0,1.000000,1.000000)  // r4.z <- output.position.z; r4.w <- output.position.w

#line 15
mov o0.xyzw, r4.xyzw
mov o1.xy, r0.yzyy
mov o2.xy, r1.xyxx
mov o3.xy, r1.zwzz
mov o4.xy, r2.xyxx
mov o5.xy, r2.zwzz
mov o6.xy, r3.xyxx
mov o7.xy, r0.xwxx
ret 
// Approximately 67 instruction slots used
