//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer CBuffer_Pixel_Blur
// {
//
//   float2 m_tex_coord_min;            // Offset:    0 Size:     8
//   float2 m_tex_coord_max;            // Offset:    8 Size:     8
//   float m_weights[4];                // Offset:   16 Size:    52
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// g_sampler                         sampler      NA          NA             s0      1 
// g_texture                         texture  float4          2d             t0      1 
// CBuffer_Pixel_Blur                cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// TEXCOORD                 0   xy          1     NONE   float   xy  
// TEXCOORD                 1   xy          2     NONE   float   xy  
// TEXCOORD                 2   xy          3     NONE   float   xy  
// TEXCOORD                 3   xy          4     NONE   float   xy  
// TEXCOORD                 4   xy          5     NONE   float   xy  
// TEXCOORD                 5   xy          6     NONE   float   xy  
// TEXCOORD                 6   xy          7     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed | skipOptimization
dcl_constantbuffer CB0[5], dynamicIndexed
dcl_sampler s0, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_input_ps linear v1.xy
dcl_input_ps linear v2.xy
dcl_input_ps linear v3.xy
dcl_input_ps linear v4.xy
dcl_input_ps linear v5.xy
dcl_input_ps linear v6.xy
dcl_input_ps linear v7.xy
dcl_output o0.xyzw
dcl_temps 4
dcl_indexrange v1.xy 7
//
// Initial variable locations:
//   v0.x <- input.position.x; v0.y <- input.position.y; v0.z <- input.position.z; v0.w <- input.position.w; 
//   v1.x <- input.tex_coord[0].x; v1.y <- input.tex_coord[0].y; 
//   v2.x <- input.tex_coord[1].x; v2.y <- input.tex_coord[1].y; 
//   v3.x <- input.tex_coord[2].x; v3.y <- input.tex_coord[2].y; 
//   v4.x <- input.tex_coord[3].x; v4.y <- input.tex_coord[3].y; 
//   v5.x <- input.tex_coord[4].x; v5.y <- input.tex_coord[4].y; 
//   v6.x <- input.tex_coord[5].x; v6.y <- input.tex_coord[5].y; 
//   v7.x <- input.tex_coord[6].x; v7.y <- input.tex_coord[6].y; 
//   o0.x <- <main return value>.x; o0.y <- <main return value>.y; o0.z <- <main return value>.z; o0.w <- <main return value>.w
//
#line 13 "C:\Users\cafeed28\Development\RmlUi\Backends\RmlUi_D3D11\shader_pixel_blur.hlsl"
mov r0.xyzw, l(0,0,0,0)  // r0.x <- color.x; r0.y <- color.y; r0.z <- color.z; r0.w <- color.w

#line 15
mov r1.x, l(0)  // r1.x <- i
mov r2.xyzw, r0.xyzw  // r2.x <- color.x; r2.y <- color.y; r2.z <- color.z; r2.w <- color.w
mov r1.y, r1.x  // r1.y <- i
loop 
  ilt r1.z, r1.y, l(7)
  breakc_z r1.z

#line 16
  ge r1.zw, v[r1.y + 1].xxxy, cb0[0].xxxy
  movc r1.zw, r1.zzzw, l(0,0,1.000000,1.000000), l(0,0,0,0)
  ge r3.xy, cb0[0].zwzz, v[r1.y + 1].xyxx
  movc r3.xy, r3.xyxx, l(1.000000,1.000000,0,0), l(0,0,0,0)
  mul r1.zw, r1.zzzw, r3.xxxy  // r1.z <- in_region.x; r1.w <- in_region.y

#line 17
  sample_indexable(texture2d)(float,float,float,float) r3.xyzw, v[r1.y + 1].xyxx, t0.xyzw, s0
  mul r3.xyzw, r1.zzzz, r3.xyzw
  mul r3.xyzw, r1.wwww, r3.xyzw
  ineg r1.z, l(4)
  iadd r1.z, r1.z, r1.y
  iadd r1.z, r1.z, l(1)
  ineg r1.w, r1.z
  imax r1.z, r1.w, r1.z
  mul r3.xyzw, r3.xyzw, cb0[r1.z + 1].xxxx
  add r2.xyzw, r2.xyzw, r3.xyzw

#line 18
  iadd r1.y, r1.y, l(1)
endloop 

#line 20
mov o0.xyzw, r2.xyzw
ret 
// Approximately 26 instruction slots used
