//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer CBuffer_Pixel_ColorMatrix
// {
//
//   float4x4 m_color_matrix;           // Offset:    0 Size:    64
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// g_sampler                         sampler      NA          NA             s0      1 
// g_texture                         texture  float4          2d             t0      1 
// CBuffer_Pixel_ColorMatrix         cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed | skipOptimization
dcl_constantbuffer CB0[4], immediateIndexed
dcl_sampler s0, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_input_ps linear v1.xy
dcl_output o0.xyzw
dcl_temps 3
//
// Initial variable locations:
//   v0.x <- input.position.x; v0.y <- input.position.y; v0.z <- input.position.z; v0.w <- input.position.w; 
//   v1.x <- input.tex_coord.x; v1.y <- input.tex_coord.y; 
//   o0.x <- <main return value>.x; o0.y <- <main return value>.y; o0.z <- <main return value>.z; o0.w <- <main return value>.w
//
#line 20 "C:\Users\cafeed28\Development\RmlUi\Backends\RmlUi_D3D11\shader_pixel_color_matrix.hlsl"
sample_indexable(texture2d)(float,float,float,float) r0.xyzw, v1.xyxx, t0.xyzw, s0  // r0.x <- tex_color.x; r0.y <- tex_color.y; r0.z <- tex_color.z; r0.w <- tex_color.w

#line 21
mul r1.xyz, r0.xxxx, cb0[0].xyzx
mul r2.xyz, r0.yyyy, cb0[1].xyzx
add r1.xyz, r1.xyzx, r2.xyzx
mul r0.xyz, r0.zzzz, cb0[2].xyzx
add r0.xyz, r0.xyzx, r1.xyzx
mul r1.xyz, r0.wwww, cb0[3].xyzx
add r0.xyz, r0.xyzx, r1.xyzx  // r0.x <- transformed_color.x; r0.y <- transformed_color.y; r0.z <- transformed_color.z

#line 23
mov o0.xyz, r0.xyzx
mov o0.w, r0.w
ret 
// Approximately 11 instruction slots used
