//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xy          0     NONE   float   xy  
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
vs_5_0
dcl_globalFlags refactoringAllowed | skipOptimization
dcl_input v0.xy
dcl_input v1.xy
dcl_output_siv o0.xyzw, position
dcl_output o1.xy
dcl_temps 2
//
// Initial variable locations:
//   v0.x <- input.position.x; v0.y <- input.position.y; 
//   v1.x <- input.tex_coord.x; v1.y <- input.tex_coord.y; 
//   o1.x <- <main return value>.tex_coord.x; o1.y <- <main return value>.tex_coord.y; 
//   o0.x <- <main return value>.position.x; o0.y <- <main return value>.position.y; o0.z <- <main return value>.position.z; o0.w <- <main return value>.position.w
//
#line 6 "C:\Users\cafeed28\Development\RmlUi\Backends\RmlUi_D3D11\shader_vertex_passthrough.hlsl"
mov r0.xy, v0.xyxx  // r0.x <- output.position.x; r0.y <- output.position.y
mov r0.zw, l(0,0,0,1.000000)  // r0.z <- output.position.z; r0.w <- output.position.w

#line 7
mov r1.xy, v1.xyxx  // r1.x <- output.tex_coord.x; r1.y <- output.tex_coord.y

#line 9
mov o0.xyzw, r0.xyzw
mov o1.xy, r1.xyxx
ret 
// Approximately 6 instruction slots used
