//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer CBuffer_Pixel_DropShadow
// {
//
//   float2 m_tex_coord_min;            // Offset:    0 Size:     8 [unused]
//   float2 m_tex_coord_max;            // Offset:    8 Size:     8 [unused]
//   float4 m_color;                    // Offset:   16 Size:    16
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// g_sampler                         sampler      NA          NA             s0      1 
// g_texture                         texture  float4          2d             t0      1 
// CBuffer_Pixel_DropShadow          cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed | skipOptimization
dcl_constantbuffer CB0[2], immediateIndexed
dcl_sampler s0, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_input_ps linear v1.xy
dcl_output o0.xyzw
dcl_temps 1
//
// Initial variable locations:
//   v0.x <- input.position.x; v0.y <- input.position.y; v0.z <- input.position.z; v0.w <- input.position.w; 
//   v1.x <- input.tex_coord.x; v1.y <- input.tex_coord.y; 
//   o0.x <- <main return value>.x; o0.y <- <main return value>.y; o0.z <- <main return value>.z; o0.w <- <main return value>.w
//
#line 14 "C:\Users\cafeed28\Development\RmlUi\Backends\RmlUi_D3D11\shader_pixel_drop_shadow.hlsl"
mov r0.xy, l(1.000000,1.000000,0,0)  // r0.x <- in_region.x; r0.y <- in_region.y

#line 15
sample_indexable(texture2d)(float,float,float,float) r0.z, v1.xyxx, t0.xywz, s0
mul r0.x, r0.x, r0.z
mul r0.x, r0.y, r0.x
mul o0.xyzw, r0.xxxx, cb0[1].xyzw
ret 
// Approximately 6 instruction slots used
