#define MAX_NUM_STOPS 16
#define BLUR_SIZE 7
#define BLUR_NUM_WEIGHTS ((BLUR_SIZE + 1) / 2)

#define GRADIENT_LINEAR 0
#define GRADIENT_RADIAL 1
#define GRADIENT_CONIC 2
#define GRADIENT_REPEATING_LINEAR 3
#define GRADIENT_REPEATING_RADIAL 4
#define GRADIENT_REPEATING_CONIC 5

#define PI 3.14159265